markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "footnotes"]
highlighter: pygments
paginate: 5
baseurl: /
permalink: /:title
paginate_path: "/page/:num/"
author_dir: author
category_dir: tag

exclude: [README.md, LICENSE, vendor, Gemfile]

gems:
  - jekyll-sitemap
  - jekyll-minifier


# ########################### #
# Configure beneath this line #
# ########################### #

name: Steven Thuriot.be
description: Thoughts, stories and ideas.
meta_description: Blogging about things on your new Jekyll site
url: localhost:4000
scheme: http #mainly used for xml feeds


logo: //cdn.thuriot.be/Avatars/Raven.jpg
cover: //cdn.thuriot.be/Wall2.png
disqus: false
author: steven
language: English

# ########################### #
